.TH fi_shm 7 "2016\-02\-02" "Libfabric Programmer\[aq]s Manual" "\@VERSION\@"
.SH NAME
.PP
The SHM Fabric Provider
.SH OVERVIEW
.PP
The \f[I]shm\f[] provider runs over the shm mechanisms (shmget/shmat)
.PP
.SH SUPPORTED FEATURES
.PP
The shm provider supports a subset of OFI features.
.PP
\f[I]Endpoint types\f[] : FI_EP_RDM
.PP
\f[I]Endpoint capabilities\f[] : FI_TAGGED
.PP
.SH SEE ALSO
.PP
\f[C]fabric\f[](7), \f[C]fi_provider\f[](7),
.SH AUTHORS
OpenFabrics.
